# Generated by Django 4.1 on 2022-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='imagen',
            field=models.ImageField(upload_to='regristros visuales', verbose_name='Imagen del defecto'),
        ),
    ]
