# Generated by Django 4.1 on 2022-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_informacion_nombre_imagen_informacion_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='imagen',
            field=models.ImageField(upload_to='imagenes', verbose_name='Imagen del defecto'),
        ),
    ]
