# Generated by Django 4.1 on 2022-10-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_informacion_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='upload_to',
            field=models.CharField(max_length=70, verbose_name='Fecha y hora de subida'),
        ),
    ]
