# Generated by Django 4.1 on 2022-10-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_informacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=70, verbose_name='Usuario')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
