# Generated by Django 4.1 on 2022-10-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_user',
        ),
        migrations.AlterField(
            model_name='calles',
            name='calle',
            field=models.CharField(blank=True, max_length=70, primary_key=True, serialize=False, verbose_name='Registros de calles'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen del defecto'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='nombre_imagen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la imagen'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado del analis'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='upload_to',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Fecha y hora de subida'),
        ),
    ]
