# Generated by Django 4.1 on 2022-10-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_login_user_alter_calles_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='callefinal',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Registros de calles'),
        ),
        migrations.DeleteModel(
            name='CALLES',
        ),
    ]
